routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Route::get('/admin', function () {
    return view('layouts.vali');
});

Route::resource('order', 'OrdersController');
Route::resource('category', 'CategoryController');
Route::resource('vendors', 'VendorController');
Route::resource('request-order', 'RequestOrderController');
Route::put('request-order/update/{id}', 'RequestOrderController@update')->name('approve.order');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Vendor.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Vendor extends Model
{
    protected $guarded = [];

    public function order()
    {
        return $this->hasMany(Orders::class);
    }
}

app/Http/Controllers/VendorController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreVendorPost;
use App\Vendor;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;

class VendorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $vendors = Vendor::latest()->get();


        return view('vendors.index', compact('vendors'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('vendors.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreVendorPost $request)
    {
        $validated = $request->validated();
        try {
            Vendor::create($validated);
            Session::flash('success', 'Create Vendor Success');
            return redirect()->route('vendors.index');
        } catch (\Exception $exception) {
            Session::flash('error', 'Created Vendor Failed');
            return redirect()->route('vendors.index');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Vendor  $vendor
     * @return \Illuminate\Http\Response
     */
    public function show(Vendor $vendor)
    {
        return view('vendors.show', compact('vendor'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Vendor  $vendor
     * @return \Illuminate\Http\Response
     */
    public function edit(Vendor $vendor)
    {
        return view('vendors.edit', compact('vendor'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Vendor  $vendor
     * @return \Illuminate\Http\Response
     */
    public function update(StoreVendorPost $request, Vendor $vendor)
    {
        $validated = $request->validated();
        try {
            $vendor->update($validated);
            Session::flash('success', 'Update Vendor Success');
            return redirect()->route('vendors.index');
        } catch (\Exception $exception) {
            Session::flash('error', 'Update Vendor Failed');
            return redirect()->route('vendors.index');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Vendor  $vendor
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $vendor = Vendor::find($id);
        try {
            $vendor->delete();
            Session::flash('success', 'Delete Vendor Success');
            return redirect()->route('vendors.index');
        } catch (\Exception $exception) {
            Session::flash('error', 'Delete Vendor Failed');
            return redirect()->route('vendors.index');
        }
    }
}

resources/views/vendors/create.blade.php
@extends('dashboard.layout')
@section('header')
    Buat Vendor
@endsection
@section('content-dashboard')

    <div class="row">
        <div class="col-md-6">
            <div class="tile">
                <form action="{{ route('vendors.store') }}" method="POST">
                    @csrf
                    <div class="form-group">
                        <label for="exampleInputEmail1">Nama Vendor</label>
                        <input class="form-control" id="name" name="nama" type="text"  placeholder="Enter name">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Alamat</label>
                        <textarea name="alamat" id="" cols="20" rows="5" class="form-control">

                        </textarea>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">No Hp</label>
                        <input class="form-control" id="name" name="nohp" type="text"  placeholder="Enter name">
                    </div>

                    <div class="tile-footer">
                        <button class="btn btn-primary" type="submit">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

@endsection

resources/views/vendors/edit.blade.php
@extends('dashboard.layout')
@section('header')
    Edit Vendor - {{ $vendor->nama }}
@endsection
@section('content-dashboard')

    <div class="row">
        <div class="col-md-6">
            <div class="tile">
                <form action="{{ route('vendors.update', $vendor->id) }}" method="POST">
                    @csrf
                    @method('PUT')
                    <div class="form-group">
                        <label for="exampleInputEmail1">Nama Vendor</label>
                        <input class="form-control" id="name" value="{{ $vendor->nama }} " name="nama" type="text"  placeholder="Enter name">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Alamat</label>
                        <textarea name="alamat" id="" cols="20" rows="10" class="form-control">
                            {{ $vendor->alamat }}
                        </textarea>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">No Hp</label>
                        <input class="form-control" id="name" value="{{ $vendor->nohp }}" name="nohp" type="text"  placeholder="Enter name">
                    </div>

                    <div class="tile-footer">
                        <button class="btn btn-primary" type="submit">Update</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

@endsection

resources/views/vendors/index.blade.php
@extends('dashboard.layout')
@section('header')
    Daftar Vendor
@endsection
@section('content-dashboard')

    <div class="row">
        <div class="col-md-12">

            <div class="tile">
                <div class="row">
                    <div class="col-md-12 mb-2">
                        <div class="float-right">
                            <a href="{{ route('vendors.create') }}" class="btn btn-outline-primary">Add Vendor</a>
                        </div>
                    </div>
                </div>
                <div class="tile-body">
                    <table class="table table-hover table-bordered" id="sampleTable">
                        <thead>
                        <tr>
                            <th>No</th>
                            <th>Name</th>
                            <th>Alamat</th>
                            <th>No Hp</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        @forelse($vendors as $vendor)
                            <tr>
                                <td width="10%">{{ $loop->iteration }}</td>
                                <td>{{ $vendor->nama }}</td>
                                <td>{{ $vendor->alamat }}</td>
                                <td>{{ $vendor->nohp }}</td>
                                <td width="25%">

                                    <a href="{{ route('vendors.edit', $vendor->id) }}" class="btn btn-sm badge-success">Edit</a>
                                    <button type="button" onclick="deleteItem('{{ $vendor->id }}')" id="delete"
                                            class="btn btn-sm badge-danger">Delete
                                    </button>
                                </td>
                            </tr>
                        @empty
                            <tr>
                                <td colspan="4" class="text-center">Tidak ada data</td>
                            </tr>
                        @endforelse

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    @push('js')
        <script src="{{ asset('vendor/js/plugins/pace.min.js') }}"></script>
        <!-- Page specific javascripts-->
        <!-- Data table plugin-->
        <script type="text/javascript" src="{{ asset('vendor/js/plugins/jquery.dataTables.min.js') }}"></script>
        <script type="text/javascript" src="{{ asset('vendor/js/plugins/dataTables.bootstrap.min.js') }}"></script>
        <script type="text/javascript">$('#sampleTable').DataTable();</script>
        <script>

            function deleteItem(id) {
                let theUrl = "{{ route('vendors.destroy', ':id_vendor') }}"
                theUrl = theUrl.replace(':id_vendor', id);

                console.log(theUrl);
                swal({
                    title: "Apakah anda yakin?",
                    text: "Menghapus file ini",
                    type: "warning",
                    showCancelButton: true,
                    confirmButtonText: "Yes, delete it!",
                    cancelButtonText: "No, cancel plx!",
                    closeOnConfirm: false,
                    closeOnCancel: false
                }, function (isConfirm) {
                    if (isConfirm) {
                        $.ajax({
                            type: "POST",
                            url: theUrl,
                            data: {
                                "_method": 'DELETE',
                            },
                            success: function (data) {
                                swal("Deleted!", "Data Sukses di delete", "success");
                                window.location.reload()
                            },
                            error: function (data) {
                                console.log(data);
                                swal("Failed", "File gagal di delete)", "error");
                            }
                        })

                    } else {
                        swal("Cancelled", "File gagal di delete)", "error");
                    }
                });
            }

        </script>
    @endpush
@endsection